import { Property, PropertyType, PropertyStatus, ListingType, BlogPost } from './types';

const allProperties = Object.values(
    import.meta.glob("./src/assets/img/property-*.png", {
      eager: true,
      import: "default",
    })
  ) as string[];
  



export const LOCATIONS = ['Hirapur', 'Saraidhela', 'Bank More', 'Dhansar', 'Bartand', 'Steel Gate', 'Kusum Vihar', 'Govindpur', 'Wasseypur', 'Jharia'];

export const SUGGESTED_AMENITIES = [
    'Car Parking', '24/7 Security', 'Power Backup', 'Lift', 'Gymnasium', 
    'Swimming Pool', 'Club House', 'Garden', 'Jogging Track', 'CCTV Surveillance',
    'Intercom', 'Fire Safety', 'Water Supply', 'Gas Pipeline', 'Vastu Compliant',
    'Kids Play Area', 'Banquet Hall', 'Wifi', 'Maintenance Staff', 'Rainwater Harvesting'
];

export const MOCK_PROPERTIES: Property[] = [
    {
        id: '1',
        title: 'Luxury 3BHK Apartment in Hirapur',
        description: 'Spacious 3BHK flat with modern amenities, located in the heart of Hirapur. Close to schools and markets.',
        price: 45,
        location: 'Hirapur',
        type: PropertyType.FLAT,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        bedrooms: 3,
        bathrooms: 2,
        area: 1450,
        images: [
            allProperties[0], allProperties[3], allProperties[5], allProperties[6], allProperties[10], allProperties[5], allProperties[17], allProperties[29],
        ],
        amenities: ['Parking', 'Lift', 'Power Backup', '24/7 Security'],
        featured: true,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '2',
        title: 'Commercial Shop at Bank More',
        description: 'Prime location commercial space suitable for retail or office. High footfall area near the main chowk.',
        price: 85,
        location: 'Bank More',
        type: PropertyType.COMMERCIAL,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        area: 400,
        images: [allProperties[2]],
        amenities: ['Water Supply', 'Main Road Facing', 'Fire Safety'],
        featured: true,
        newLaunch: false,
        primeCommercial: true,
        agentContact: '+91 9876543210'
    },
    {
        id: '3',
        title: 'Premium Villa in Saraidhela',
        description: 'Independent villa with garden and terrace. Peaceful locality near Big Bazaar and Asian Jalan Hospital.',
        price: 120,
        location: 'Saraidhela',
        type: PropertyType.VILLA,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        bedrooms: 4,
        bathrooms: 4,
        area: 2800,
        images: [allProperties[22]],
        amenities: ['Garden', 'Private Parking', 'Gated Community', 'Servant Quarter'],
        featured: true,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '4',
        title: 'Affordable Plot near ISM',
        description: 'Residential plot available for immediate construction. Good investment opportunity near IIT ISM.',
        price: 25,
        location: 'Saraidhela',
        type: PropertyType.PLOT,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        area: 1200,
        images: [allProperties[20]],
        amenities: ['Boundary Wall', 'Road Connectivity', 'Electricity'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '5',
        title: 'Skyline Heights - 2BHK Flat',
        description: 'Upcoming project in Bartand with state-of-the-art facilities. Book now for early bird offer.',
        price: 32,
        location: 'Bartand',
        type: PropertyType.FLAT,
        status: PropertyStatus.UNDER_CONSTRUCTION,
        listingType: ListingType.BUY,
        bedrooms: 2,
        bathrooms: 2,
        area: 1100,
        images: [allProperties[37]],
        amenities: ['Club House', 'Gym', 'Swimming Pool', 'Jogging Track'],
        featured: true,
        newLaunch: true,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '6',
        title: 'Office Space in Steel Gate',
        description: 'Modern office space fully furnished, ready to move in. Ideal for IT companies or consultants.',
        price: 40,
        location: 'Steel Gate',
        type: PropertyType.COMMERCIAL,
        status: PropertyStatus.READY,
        listingType: ListingType.RENT,
        area: 800,
        images: [allProperties[23]],
        amenities: ['AC', 'Conference Room', 'Wi-Fi', 'Cafeteria'],
        featured: false,
        newLaunch: false,
        primeCommercial: true,
        agentContact: '+91 9876543210'
    },
    {
        id: '7',
        title: 'Duplex Home in Kusum Vihar',
        description: 'Beautifully designed duplex with modern interiors. Located in a posh colony.',
        price: 75,
        location: 'Kusum Vihar',
        type: PropertyType.VILLA,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        bedrooms: 3,
        bathrooms: 3,
        area: 2100,
        images: [allProperties[7]],
        amenities: ['Modular Kitchen', 'Terrace Garden', 'CCTV'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '8',
        title: 'Investment Plot in Govindpur',
        description: 'Large plot on GT Road, excellent for commercial or residential development.',
        price: 55,
        location: 'Govindpur',
        type: PropertyType.PLOT,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        area: 2400,
        images: [allProperties[9]],
        amenities: ['Highway Access', 'Water Connection'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '9',
        title: 'Luxury 4BHK Penthouse',
        description: 'Exclusive penthouse with panoramic view of Dhanbad. Premium finishings.',
        price: 150,
        location: 'Dhansar',
        type: PropertyType.FLAT,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        bedrooms: 4,
        bathrooms: 4,
        area: 3200,
        images: [allProperties[13]],
        amenities: ['Private Pool', 'Gym', 'Concierge', 'Smart Home'],
        featured: true,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '10',
        title: 'Commercial Showroom - Center Point',
        description: 'Ground floor showroom space available for lease. Best visibility in town.',
        price: 120,
        location: 'Bank More',
        type: PropertyType.COMMERCIAL,
        status: PropertyStatus.READY,
        listingType: ListingType.RENT,
        area: 1500,
        images: [allProperties[19]],
        amenities: ['Glass Facade', 'Parking', 'Power Backup'],
        featured: true,
        newLaunch: false,
        primeCommercial: true,
        agentContact: '+91 9876543210'
    },
    {
        id: '11',
        title: '1BHK Budget Flat for Students',
        description: 'Compact 1BHK near colleges. Ideal for students or bachelors.',
        price: 8,
        location: 'Hirapur',
        type: PropertyType.FLAT,
        status: PropertyStatus.READY,
        listingType: ListingType.RENT,
        bedrooms: 1,
        bathrooms: 1,
        area: 600,
        images: [allProperties[16]],
        amenities: ['Water Supply', 'Security'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '12',
        title: 'Green Valley Apartments',
        description: 'New residential complex under construction. Green living concept.',
        price: 38,
        location: 'Dhansar',
        type: PropertyType.FLAT,
        status: PropertyStatus.UNDER_CONSTRUCTION,
        listingType: ListingType.BUY,
        bedrooms: 3,
        bathrooms: 2,
        area: 1350,
        images: [allProperties[8]],
        amenities: ['Park', 'Solar Lighting', 'Rainwater Harvesting'],
        featured: false,
        newLaunch: true,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '13',
        title: 'Warehousing Space',
        description: 'Large godown/warehouse available on the outskirts. Truck accessibility.',
        price: 25,
        location: 'Govindpur',
        type: PropertyType.COMMERCIAL,
        status: PropertyStatus.READY,
        listingType: ListingType.RENT,
        area: 5000,
        images: [allProperties[1]],
        amenities: ['Loading Dock', 'High Ceiling'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '14',
        title: 'Corner Plot in Wasseypur',
        description: 'Residential corner plot in a developing neighborhood.',
        price: 18,
        location: 'Wasseypur',
        type: PropertyType.PLOT,
        status: PropertyStatus.READY,
        listingType: ListingType.BUY,
        area: 1500,
        images: [allProperties[2]],
        amenities: ['Corner Plot', 'Drainage'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '15',
        title: 'Furnished 2BHK Rent',
        description: 'Fully furnished flat available for families. Near schools.',
        price: 15,
        location: 'Saraidhela',
        type: PropertyType.FLAT,
        status: PropertyStatus.READY,
        listingType: ListingType.RENT,
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        images: [allProperties[38]],
        amenities: ['Furniture', 'AC', 'TV', 'Fridge'],
        featured: false,
        newLaunch: false,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    },
    {
        id: '16',
        title: 'Shree Tower - 3BHK',
        description: 'Luxurious 3BHK in the tallest tower of Dhanbad. Pre-launch offer.',
        price: 60,
        location: 'Bank More',
        type: PropertyType.FLAT,
        status: PropertyStatus.UNDER_CONSTRUCTION,
        listingType: ListingType.BUY,
        bedrooms: 3,
        bathrooms: 3,
        area: 1600,
        images: [allProperties[39]],
        amenities: ['Sky Lounge', 'Infinity Pool', 'Valet Parking'],
        featured: true,
        newLaunch: true,
        primeCommercial: false,
        agentContact: '+91 9876543210'
    }
];

export const MOCK_BLOGS: BlogPost[] = [
    {
        id: '1',
        title: 'Property Trends in Dhanbad 2025',
        excerpt: 'Analysis of the rising real estate market in the coal capital of India.',
        content: 'Dhanbad is witnessing a surge in demand for gated communities...',
        date: '2023-10-15',
        author: 'Rahul Sharma',
        imageUrl: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: '2',
        title: 'Investment Tips for First Time Buyers',
        excerpt: 'What to look for before buying your dream home in Jharkhand.',
        content: 'Location, builder reputation, and legal checks are paramount...',
        date: '2023-10-10',
        author: 'Priya Singh',
        imageUrl: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=600&q=80'
    }
];